#include <string>
std::string default_vertex_shader =
    "#version 410 core\n"
    "layout(location = 0) in vec3 position;\n"
    "layout(location = 1) in vec3 color;\n"
    "layout(location = 2) in vec3 normal;\n"
    "layout(location = 3) in vec2 texture_coord;\n"
    "\n"
    "uniform mat4 fullTransformMatrix;\n"
    "uniform mat4 rotationMatrix;\n"
    "uniform mat4 modelToWorldMatrix;\n"
    "\n"
    "out vec3 theColor;\n"
    "out vec3 theNormal;\n"
    "out vec3 pos;\n"
    "out vec2 textureCoord;\n"
    "void main()\n"
    "{\n"
    "   vec4 v = vec4(position, 1.0);\n"
    "   vec4 newPosition = fullTransformMatrix*v;\n"
    "   gl_Position = newPosition;\n"
    "   theColor = color;\n"
    "   theNormal = vec3(rotationMatrix * vec4(normal, 0.0));\n"
    "   pos = vec3(modelToWorldMatrix*vec4(position, 1.0));\n"
    "   textureCoord = texture_coord;\n"
    "// theNormal = vec3(1, 1, 1);\n"
    "}";
std::string default_fragment_shader =
    "#version 410 core\n"
    "in vec3 theColor;\n"
    "in vec3 theNormal;\n"
    "in vec3 pos;\n"
    "in vec2 textureCoord;\n"
    "out vec4 color;\n"
    "\n"
    "uniform vec3 lightDirection;\n"
    "uniform vec3 cameraLocation;\n"
    "uniform sampler2D text;\n"
    "uniform int isTexture;\n"
    "uniform float specMultiplier;\n"
    "void main() {\n"
    "    // color = vec4(1.0f, 0.5f, 0.0f, 1.0f);\n"
    "    float intensity = dot(lightDirection, theNormal);\n"
    "    vec4 intensity_vec = clamp(vec4(intensity, intensity, intensity, "
    "1.0), 0.1, 1.0);\n"
    "\n"
    "    // specular light\n"
    "    vec3 vertexToEye = normalize(cameraLocation - pos);\n"
    "    vec3 reflected = normalize(reflect(-lightDirection, theNormal));\n"
    "    float specFactor = pow(clamp(dot(vertexToEye, reflected), 0.0, 1.0), "
    "100) * specMultiplier;\n"
    "\n"
    "    vec4 specColor = vec4(specFactor, specFactor, specFactor, 1.0);\n"
    "\n"
    "    if (isTexture == 0) {\n"
    "        color = clamp(vec4(theColor, 1.0) * intensity_vec + specColor, "
    "0.0, 1.0);\n"
    "    } else if (isTexture == 1){\n"
    "        // vec4 sampled = vec4(1.0, 1.0, 1.0, texture(text, "
    "textureCoord).r);\n"
    "        vec4 sampled = texture(text, textureCoord);\n"
    "        color = clamp(vec4(theColor, 1.0) * intensity_vec + specColor, "
    "0.0, 1.0) * sampled;\n"
    "        // color = clamp(vec4(theColor, 1.0), 0.0, 1.0) * sampled;\n"
    "        // color = clamp(vec4(theColor, 1.0), 0.0, 1.0);\n"
    "    } else {\n"
    "        vec4 sampled = vec4(1.0, 1.0, 1.0, texture(text, "
    "textureCoord).r);\n"
    "        color = clamp(vec4(theColor, 1.0) * intensity_vec + specColor, "
    "0.0, 1.0) * sampled;\n"
    "    }\n"
    "    // color = clamp(specColor, 0.0, 1.0);\n"
    "    // color = vec4(theColor, 1.0);\n"
    "}\n";

void set_default_vertex_shader(std::string vertex_shader_src) {
    default_vertex_shader = vertex_shader_src;
}

void set_default_fragment_shader(std::string fragment_shader_src) {
    default_fragment_shader = fragment_shader_src;
}
